# Generated by Django 4.2.26 on 2025-11-12 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount",
                        max_digits=10,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="usd",
                        help_text="Payment currency code",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "payment_provider",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("other", "Other"),
                        ],
                        default="stripe",
                        help_text="Payment gateway used",
                        max_length=20,
                        verbose_name="Payment Provider",
                    ),
                ),
                (
                    "provider_session_id",
                    models.CharField(
                        blank=True,
                        help_text="Payment provider session ID (e.g., Stripe Checkout Session ID)",
                        max_length=255,
                        null=True,
                        verbose_name="Provider Session ID",
                    ),
                ),
                (
                    "provider_payment_id",
                    models.CharField(
                        blank=True,
                        help_text="Payment provider payment ID (e.g., Stripe Payment Intent ID)",
                        max_length=255,
                        null=True,
                        verbose_name="Provider Payment ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="created",
                        help_text="Current payment status",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "test_bank",
                    models.ForeignKey(
                        help_text="Test bank being purchased",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="catalog.testbank",
                        verbose_name="Test Bank",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who made the payment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchased_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the purchase was completed",
                        verbose_name="Purchased At",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether purchase is active",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When purchase expires (null for lifetime access)",
                        null=True,
                        verbose_name="Expires At",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        help_text="Payment transaction for this purchase",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase",
                        to="payments.payment",
                        verbose_name="Payment",
                    ),
                ),
                (
                    "test_bank",
                    models.ForeignKey(
                        help_text="Test bank that was purchased",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="catalog.testbank",
                        verbose_name="Test Bank",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who made the purchase",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase",
                "verbose_name_plural": "Purchases",
                "ordering": ["-purchased_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="payments_pu_user_id_55c69e_idx",
                    ),
                    models.Index(
                        fields=["test_bank", "is_active"],
                        name="payments_pu_test_ba_b1d20c_idx",
                    ),
                    models.Index(
                        fields=["purchased_at"], name="payments_pu_purchas_51f2f0_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["user", "status"], name="payments_pa_user_id_01767a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["provider_session_id"], name="payments_pa_provide_36806b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["created_at"], name="payments_pa_created_b8a300_idx"
            ),
        ),
    ]
