# Generated by Django 4.2.26 on 2025-11-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_provider",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("paypal", "PayPal"),
                    ("free", "Free"),
                    ("other", "Other"),
                ],
                default="stripe",
                help_text="Payment gateway used",
                max_length=20,
                verbose_name="Payment Provider",
            ),
        ),
    ]
