# Generated by Django 4.2.26 on 2026-03-19 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_add_order_coupon_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_provider",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("moyasar", "Moyasar"),
                    ("paypal", "PayPal"),
                    ("free", "Free"),
                    ("other", "Other"),
                ],
                default="stripe",
                help_text="Payment gateway used",
                max_length=20,
                verbose_name="Payment Provider",
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="payment",
            field=models.ForeignKey(
                help_text="Payment transaction for this purchase",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to="payments.payment",
                verbose_name="Payment",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.UniqueConstraint(
                fields=("payment", "test_bank"),
                name="unique_purchase_per_payment_testbank",
            ),
        ),
    ]
