# Generated by Django 5.2.9 on 2026-03-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0005_purchase_fk_for_packages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_provider",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("moyasar", "Moyasar"),
                    ("tap", "Tap"),
                    ("paypal", "PayPal"),
                    ("free", "Free"),
                    ("other", "Other"),
                ],
                default="stripe",
                help_text="Payment gateway used",
                max_length=20,
                verbose_name="Payment Provider",
            ),
        ),
    ]
