# Generated by Django 4.2.26 on 2026-04-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0007_moyasar_legacy_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("stripe", "Stripe"), ("tap", "Tap")],
                        max_length=20,
                        verbose_name="Provider",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        help_text="e.g. evt_1Xxx for Stripe, charge id for Tap",
                        max_length=255,
                        verbose_name="Provider Event ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=100, verbose_name="Event Type"),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Processed Webhook Event",
                "verbose_name_plural": "Processed Webhook Events",
                "indexes": [
                    models.Index(
                        fields=["provider", "event_id"],
                        name="payments_pr_provide_2196cf_idx",
                    ),
                    models.Index(
                        fields=["received_at"], name="payments_pr_receive_dd7491_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="processedwebhookevent",
            constraint=models.UniqueConstraint(
                fields=("provider", "event_id"), name="unique_provider_event"
            ),
        ),
    ]
