# Generated by Django 4.2.26 on 2026-04-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0008_processedwebhookevent_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProcessedWebhookEvent",
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_provider",
            field=models.CharField(
                choices=[("paylink", "Paylink"), ("free", "Free"), ("other", "Other")],
                default="paylink",
                help_text="Payment gateway used",
                max_length=20,
                verbose_name="Payment Provider",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="provider_payment_id",
            field=models.CharField(
                blank=True,
                help_text="Payment provider payment ID",
                max_length=255,
                null=True,
                verbose_name="Provider Payment ID",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="provider_session_id",
            field=models.CharField(
                blank=True,
                help_text="Payment provider session ID",
                max_length=255,
                null=True,
                verbose_name="Provider Session ID",
            ),
        ),
    ]
