# Generated by Django 4.2.26 on 2026-04-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0009_paylink_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="card_last_four",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Last four digits of the card used",
                max_length=4,
                verbose_name="Card Last 4",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. MADA, VISA, STC_PAY, MASTERCARD",
                max_length=50,
                verbose_name="Payment Method",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="receipt_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Link to the payment receipt from the gateway",
                max_length=500,
                verbose_name="Receipt URL",
            ),
        ),
    ]
