# Cloud Build configuration for Google Cloud Platform
# Builds Docker image and deploys to Cloud Run

steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/exam-stellar:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/exam-stellar:latest'
      - '-f'
      - 'Dockerfile'
      - '.'

  # Push images to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/exam-stellar:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/exam-stellar:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'exam-stellar'
      - '--image'
      - 'gcr.io/$PROJECT_ID/exam-stellar:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DB_HOST=/cloudsql/$PROJECT_ID:us-central1:exam-stellar-db,DEBUG=False'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:us-central1:exam-stellar-db'
      - '--set-secrets'
      - 'SECRET_KEY=django-secret-key:latest,DB_PASSWORD=db-password:latest'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '1'
      - '--port'
      - '8000'

images:
  - 'gcr.io/$PROJECT_ID/exam-stellar:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/exam-stellar:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

