# Generated by Django 4.2.26 on 2025-11-15 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Page title", max_length=200, verbose_name="Title"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text='URL-friendly version of the title (e.g., "about-us")',
                        max_length=200,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Page content (HTML supported)",
                        verbose_name="Content",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO meta title (defaults to title if empty)",
                        max_length=200,
                        verbose_name="Meta Title",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="SEO meta description",
                        max_length=300,
                        verbose_name="Meta Description",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        help_text="Page publication status",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Show this page in featured sections",
                        verbose_name="Is Featured",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                        verbose_name="Order",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the page was published",
                        null=True,
                        verbose_name="Published At",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User who created this page",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_pages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
                "ordering": ["order", "title"],
                "indexes": [
                    models.Index(
                        fields=["status", "is_featured"],
                        name="cms_page_status_de716a_idx",
                    ),
                    models.Index(fields=["slug"], name="cms_page_slug_f9a361_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Media title/name",
                        max_length=200,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Media description",
                        verbose_name="Description",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Upload file",
                        upload_to="cms/media/%Y/%m/%d/",
                        verbose_name="File",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("document", "Document"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("other", "Other"),
                        ],
                        default="image",
                        help_text="Media type",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alternative text for images (for accessibility and SEO)",
                        max_length=200,
                        verbose_name="Alt Text",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="User who uploaded this file",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_media",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media",
                "verbose_name_plural": "Media",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["media_type"], name="cms_media_media_t_02806a_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for this content block",
                        max_length=200,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier",
                        max_length=200,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Block content (HTML supported)",
                        verbose_name="Content",
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        default="general",
                        help_text='Type/category of this block (e.g., "header", "footer", "sidebar")',
                        max_length=50,
                        verbose_name="Block Type",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User who created this block",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_blocks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Block",
                "verbose_name_plural": "Content Blocks",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["slug", "block_type"],
                        name="cms_content_slug_9fb700_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Announcement title",
                        max_length=200,
                        verbose_name="Title",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Announcement content", verbose_name="Content"
                    ),
                ),
                (
                    "announcement_type",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="info",
                        help_text="Announcement type (affects styling)",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this announcement is currently active",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "show_on_homepage",
                    models.BooleanField(
                        default=True,
                        help_text="Display this announcement on the homepage",
                        verbose_name="Show on Homepage",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When to start showing this announcement",
                        null=True,
                        verbose_name="Start Date",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When to stop showing this announcement",
                        null=True,
                        verbose_name="End Date",
                    ),
                ),
                (
                    "link_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional link URL for the announcement",
                        verbose_name="Link URL",
                    ),
                ),
                (
                    "link_text",
                    models.CharField(
                        blank=True,
                        help_text="Text for the optional link",
                        max_length=100,
                        verbose_name="Link Text",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User who created this announcement",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "show_on_homepage"],
                        name="cms_announc_is_acti_59a917_idx",
                    )
                ],
            },
        ),
    ]
