# Generated by Django 4.2.26 on 2025-11-15 10:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="content",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Announcement content (rich text editor)",
                verbose_name="Content",
            ),
        ),
        migrations.AlterField(
            model_name="contentblock",
            name="content",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Block content (rich text editor)",
                verbose_name="Content",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="content",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Page content (rich text editor)",
                verbose_name="Content",
            ),
        ),
    ]
