# Generated by Django 4.2.26 on 2025-11-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0002_alter_announcement_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Customer name", max_length=100, verbose_name="Name"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="Customer role or job title",
                        max_length=100,
                        verbose_name="Role/Title",
                    ),
                ),
                (
                    "quote",
                    models.TextField(
                        help_text="Testimonial quote", verbose_name="Quote"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Optional customer photo",
                        null=True,
                        upload_to="cms/testimonials/%Y/%m/%d/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this testimonial is currently displayed",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                        verbose_name="Order",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "order"],
                        name="cms_testimo_is_acti_ae89bb_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Main heading for the slide",
                        max_length=200,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Subheading or description text",
                        max_length=500,
                        verbose_name="Description",
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional background image (if not provided, gradient will be used)",
                        null=True,
                        upload_to="cms/hero_slides/%Y/%m/%d/",
                        verbose_name="Background Image",
                    ),
                ),
                (
                    "gradient_from",
                    models.CharField(
                        default="#8FABD4",
                        help_text="Hex color for gradient start (e.g., #8FABD4)",
                        max_length=7,
                        verbose_name="Gradient From Color",
                    ),
                ),
                (
                    "gradient_to",
                    models.CharField(
                        default="#4A70A9",
                        help_text="Hex color for gradient end (e.g., #4A70A9)",
                        max_length=7,
                        verbose_name="Gradient To Color",
                    ),
                ),
                (
                    "primary_button_text",
                    models.CharField(
                        blank=True,
                        help_text="Text for the primary CTA button",
                        max_length=100,
                        verbose_name="Primary Button Text",
                    ),
                ),
                (
                    "primary_button_url",
                    models.CharField(
                        blank=True,
                        help_text="URL for the primary button (e.g., /categories/)",
                        max_length=200,
                        verbose_name="Primary Button URL",
                    ),
                ),
                (
                    "secondary_button_text",
                    models.CharField(
                        blank=True,
                        help_text="Text for the secondary CTA button (optional)",
                        max_length=100,
                        verbose_name="Secondary Button Text",
                    ),
                ),
                (
                    "secondary_button_url",
                    models.CharField(
                        blank=True,
                        help_text="URL for the secondary button (optional)",
                        max_length=200,
                        verbose_name="Secondary Button URL",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this slide is currently displayed",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                        verbose_name="Order",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Hero Slide",
                "verbose_name_plural": "Hero Slides",
                "ordering": ["order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "order"],
                        name="cms_herosli_is_acti_74c7d9_idx",
                    )
                ],
            },
        ),
    ]
