# Generated by Django 4.2.26 on 2025-12-11 21:25

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cms", "0003_testimonial_heroslide"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Blog post title",
                        max_length=200,
                        verbose_name="Title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text='URL-friendly version of the title (e.g., "my-first-blog-post")',
                        max_length=200,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Short summary or excerpt of the blog post",
                        max_length=500,
                        verbose_name="Excerpt",
                    ),
                ),
                (
                    "content",
                    ckeditor.fields.RichTextField(
                        blank=True,
                        help_text="Blog post content (rich text editor)",
                        verbose_name="Content",
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        help_text="Main image for the blog post",
                        null=True,
                        upload_to="cms/blog/%Y/%m/%d/",
                        verbose_name="Featured Image",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO meta title (defaults to title if empty)",
                        max_length=200,
                        verbose_name="Meta Title",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="SEO meta description",
                        max_length=300,
                        verbose_name="Meta Description",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        help_text="Publication status",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Show this post in featured sections",
                        verbose_name="Is Featured",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the blog post was published",
                        null=True,
                        verbose_name="Published At",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User who created this blog post",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_blog_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "is_featured"],
                        name="cms_blogpos_status_d9bb41_idx",
                    ),
                    models.Index(fields=["slug"], name="cms_blogpos_slug_19f322_idx"),
                    models.Index(
                        fields=["published_at"], name="cms_blogpos_publish_b6106d_idx"
                    ),
                ],
            },
        ),
    ]
