# Generated by Django 4.2.26 on 2026-04-17 15:03

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0005_blogcomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                help_text="Announcement content (rich text editor)",
                verbose_name="Content",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                help_text="Blog post content (rich text editor)",
                verbose_name="Content",
            ),
        ),
        migrations.AlterField(
            model_name="contentblock",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                help_text="Block content (rich text editor)",
                verbose_name="Content",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                help_text="Page content (rich text editor)",
                verbose_name="Content",
            ),
        ),
    ]
