# Generated by Django 4.2.26 on 2025-12-14 17:50

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ForumCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name",
                        max_length=100,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of the name",
                        max_length=100,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Category description",
                        max_length=500,
                        verbose_name="Description",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text='Icon name or emoji (e.g., "💬", "📚")',
                        max_length=50,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                        verbose_name="Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this category is visible",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Forum Category",
                "verbose_name_plural": "Forum Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ForumTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Topic title", max_length=200, verbose_name="Title"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of the title",
                        max_length=200,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "content",
                    ckeditor.fields.RichTextField(
                        help_text="Initial post content", verbose_name="Content"
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False,
                        help_text="Pin this topic to the top of the category",
                        verbose_name="Is Pinned",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Lock this topic to prevent new replies",
                        verbose_name="Is Locked",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this topic has been viewed",
                        verbose_name="Views Count",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "last_activity_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the last post was made in this topic",
                        verbose_name="Last Activity At",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User who created this topic",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_topics",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category this topic belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="forum.forumcategory",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forum Topic",
                "verbose_name_plural": "Forum Topics",
                "ordering": ["-is_pinned", "-last_activity_at"],
            },
        ),
        migrations.CreateModel(
            name="ForumPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    ckeditor.fields.RichTextField(
                        help_text="Post content", verbose_name="Content"
                    ),
                ),
                (
                    "is_edited",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this post has been edited",
                        verbose_name="Is Edited",
                    ),
                ),
                (
                    "edited_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this post was last edited",
                        null=True,
                        verbose_name="Edited At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User who wrote this post",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        help_text="Topic this post belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="forum.forumtopic",
                        verbose_name="Topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forum Post",
                "verbose_name_plural": "Forum Posts",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="forumtopic",
            index=models.Index(
                fields=["category", "is_pinned", "is_locked"],
                name="forum_forum_categor_724c31_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="forumtopic",
            index=models.Index(fields=["slug"], name="forum_forum_slug_a4acd9_idx"),
        ),
        migrations.AddIndex(
            model_name="forumpost",
            index=models.Index(
                fields=["topic", "created_at"], name="forum_forum_topic_i_66b449_idx"
            ),
        ),
    ]
