# Generated by Django 4.2.26 on 2026-04-17 15:03

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forumpost",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                help_text="Post content", verbose_name="Content"
            ),
        ),
        migrations.AlterField(
            model_name="forumtopic",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                help_text="Initial post content", verbose_name="Content"
            ),
        ),
    ]
