# Generated by Django 4.2.26 on 2025-11-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("content_manager", "Content Manager"),
                    ("editor", "Editor"),
                    ("user", "Regular User"),
                ],
                default="user",
                help_text="User role for content management permissions",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
