# Generated by Django 4.2.26 on 2025-11-12 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTestSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the practice session started",
                        verbose_name="Started At",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the practice session was completed",
                        null=True,
                        verbose_name="Completed At",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Score as percentage (0-100)",
                        max_digits=5,
                        null=True,
                        verbose_name="Score",
                    ),
                ),
                (
                    "total_questions",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of questions answered",
                        verbose_name="Total Questions",
                    ),
                ),
                (
                    "correct_answers",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of correct answers",
                        verbose_name="Correct Answers",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="in_progress",
                        help_text="Current status of the session",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Total duration of the session in seconds",
                        null=True,
                        verbose_name="Duration (seconds)",
                    ),
                ),
                (
                    "test_bank",
                    models.ForeignKey(
                        help_text="Test bank being practiced",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_sessions",
                        to="catalog.testbank",
                        verbose_name="Test Bank",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who is practicing",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Test Session",
                "verbose_name_plural": "User Test Sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="UserTestAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchased_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When access was granted",
                        verbose_name="Purchased At",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When access expires (null for lifetime access)",
                        null=True,
                        verbose_name="Expires At",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether access is currently active",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "test_bank",
                    models.ForeignKey(
                        help_text="Test bank user has access to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_accesses",
                        to="catalog.testbank",
                        verbose_name="Test Bank",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who has access",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_accesses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Test Access",
                "verbose_name_plural": "User Test Accesses",
                "ordering": ["-purchased_at"],
            },
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the answer is correct",
                        verbose_name="Is Correct",
                    ),
                ),
                (
                    "answered_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the answer was submitted",
                        verbose_name="Answered At",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="Question that was answered",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answers",
                        to="catalog.question",
                        verbose_name="Question",
                    ),
                ),
                (
                    "selected_options",
                    models.ManyToManyField(
                        help_text="Answer options selected by the user",
                        related_name="user_answers",
                        to="catalog.answeroption",
                        verbose_name="Selected Options",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Practice session this answer belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answers",
                        to="practice.usertestsession",
                        verbose_name="Session",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Answer",
                "verbose_name_plural": "User Answers",
                "ordering": ["answered_at"],
            },
        ),
        migrations.AddIndex(
            model_name="usertestsession",
            index=models.Index(
                fields=["user", "test_bank", "status"],
                name="practice_us_user_id_50c7f1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usertestsession",
            index=models.Index(
                fields=["started_at"], name="practice_us_started_a0b755_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usertestaccess",
            index=models.Index(
                fields=["user", "is_active"], name="practice_us_user_id_934228_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usertestaccess",
            index=models.Index(
                fields=["test_bank", "is_active"], name="practice_us_test_ba_ba647e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usertestaccess",
            unique_together={("user", "test_bank")},
        ),
        migrations.AddIndex(
            model_name="useranswer",
            index=models.Index(
                fields=["session", "question"], name="practice_us_session_7e3ee8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="useranswer",
            unique_together={("session", "question")},
        ),
    ]
