# Generated by Django 4.2.26 on 2025-11-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("practice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertestsession",
            name="question_order",
            field=models.JSONField(
                blank=True,
                help_text="Randomized order of question IDs for this session",
                null=True,
                verbose_name="Question Order",
            ),
        ),
    ]
