# Generated by Django 6.0.2 on 2026-02-25 01:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_certification_unique_together_and_more'),
        ('practice', '0002_usertestsession_question_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='usertestaccess',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='useranswer',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='unique_answer_per_session_question'),
        ),
        migrations.AddConstraint(
            model_name='usertestaccess',
            constraint=models.UniqueConstraint(fields=('user', 'test_bank'), name='unique_access_per_user_testbank'),
        ),
    ]
