# Generated by Django 4.2.26 on 2026-02-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("practice", "0002_usertestsession_question_order"),
    ]

    operations = [
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['answered_at'], name='practice_us_answere_idx'),
        ),
    ]
