# Generated by Django 4.2.26 on 2026-02-23 20:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("practice", "0003_add_answered_at_index"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="useranswer",
            new_name="practice_us_answere_b97501_idx",
            old_name="practice_us_answere_idx",
        ),
    ]
