# Generated by Django 4.2.26 on 2026-02-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "practice",
            "0004_rename_practice_us_answere_idx_practice_us_answere_b97501_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="useranswer",
            name="marked_for_review",
            field=models.BooleanField(
                default=False,
                help_text="Whether this question is marked for review",
                verbose_name="Marked for Review",
            ),
        ),
        migrations.AddField(
            model_name="usertestsession",
            name="time_remaining_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Time remaining in seconds (for timed exams)",
                null=True,
                verbose_name="Time Remaining (seconds)",
            ),
        ),
    ]
