# Generated by Django 4.2.26 on 2026-02-23 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0016_testbank_time_limit_minutes"),
        ("practice", "0005_useranswer_marked_for_review_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        help_text="Unique certificate identifier",
                        max_length=100,
                        unique=True,
                        verbose_name="Certificate Number",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Score percentage when certificate was earned",
                        max_digits=5,
                        verbose_name="Score",
                    ),
                ),
                (
                    "passing_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=70.0,
                        help_text="Minimum score required to earn certificate (percentage)",
                        max_digits=5,
                        verbose_name="Passing Threshold",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the certificate was issued",
                        verbose_name="Issued At",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        help_text="Generated PDF certificate file",
                        null=True,
                        upload_to="certificates/",
                        verbose_name="PDF File",
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        help_text="Practice session that earned this certificate",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to="practice.usertestsession",
                        verbose_name="Session",
                    ),
                ),
                (
                    "test_bank",
                    models.ForeignKey(
                        help_text="Test bank this certificate is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="catalog.testbank",
                        verbose_name="Test Bank",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who earned this certificate",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificate",
                "verbose_name_plural": "Certificates",
                "ordering": ["-issued_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-issued_at"],
                        name="practice_ce_user_id_f07caf_idx",
                    ),
                    models.Index(
                        fields=["test_bank"], name="practice_ce_test_ba_777fd9_idx"
                    ),
                    models.Index(
                        fields=["certificate_number"],
                        name="practice_ce_certifi_326245_idx",
                    ),
                ],
            },
        ),
    ]
