# Generated by Django 6.0.2 on 2026-02-25 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_alter_useranswer_unique_together_and_more'),
        ('practice', '0006_certificate'),
    ]

    operations = [
    ]
