# Generated by Django 4.2.26 on 2026-03-19 10:29

from django.db import migrations, models


def backfill_attempts(apps, schema_editor):
    """Set attempts_used from completed sessions; give existing users 3 extra attempts."""
    UserTestAccess = apps.get_model("practice", "UserTestAccess")
    UserTestSession = apps.get_model("practice", "UserTestSession")
    for access in UserTestAccess.objects.all():
        used = UserTestSession.objects.filter(
            user=access.user,
            test_bank=access.test_bank,
            status="completed",
        ).count()
        access.attempts_used = used
        # Existing users: allow 3 more attempts than already used (min 3)
        access.attempts_allowed = max(3, used + 3)
        access.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("practice", "0007_merge_20260225_2113"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertestaccess",
            name="attempts_allowed",
            field=models.PositiveIntegerField(
                default=3,
                help_text="Maximum number of exam attempts (e.g., 1, 3, or 999 for unlimited)",
                verbose_name="Attempts Allowed",
            ),
        ),
        migrations.AddField(
            model_name="usertestaccess",
            name="attempts_used",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of exam attempts already used",
                verbose_name="Attempts Used",
            ),
        ),
        migrations.RunPython(backfill_attempts, noop),
    ]
