# Generated by Django 4.2.26 on 2026-04-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("practice", "0008_add_attempt_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="useranswer",
            name="question_snapshot",
            field=models.JSONField(
                blank=True,
                help_text="Frozen copy of question text/options at answer time — authoritative for historical review",
                null=True,
                verbose_name="Question Snapshot",
            ),
        ),
    ]
