# Generated by Django 4.2.26 on 2025-11-12 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the category (e.g., School, College, Professional)",
                        max_length=100,
                        unique=True,
                        verbose_name="Category Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of the name",
                        max_length=100,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the category",
                        verbose_name="Description",
                    ),
                ),
                (
                    "level_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata as JSON (tags, requirements, etc.)",
                        null=True,
                        verbose_name="Level Details",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TestBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the test bank",
                        max_length=200,
                        verbose_name="Title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of the title",
                        max_length=200,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the test bank content",
                        verbose_name="Description",
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        help_text="Difficulty level of the test bank",
                        max_length=20,
                        verbose_name="Difficulty Level",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price to purchase access to this test bank",
                        max_digits=10,
                        verbose_name="Price",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this test bank is active and visible to users",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category this test bank belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_banks",
                        to="catalog.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Bank",
                "verbose_name_plural": "Test Banks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.TextField(
                        help_text="The question content", verbose_name="Question Text"
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("mcq_single", "Multiple Choice (Single Answer)"),
                            ("mcq_multi", "Multiple Choice (Multiple Answers)"),
                            ("true_false", "True/False"),
                        ],
                        default="mcq_single",
                        help_text="Type of question",
                        max_length=20,
                        verbose_name="Question Type",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Explanation shown after user answers the question",
                        verbose_name="Explanation",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this question is active",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order of this question within the test bank",
                        verbose_name="Order",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "test_bank",
                    models.ForeignKey(
                        help_text="Test bank this question belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="catalog.testbank",
                        verbose_name="Test Bank",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnswerOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option_text",
                    models.CharField(
                        help_text="The text of this answer option",
                        max_length=500,
                        verbose_name="Option Text",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this answer option is correct",
                        verbose_name="Is Correct",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order of this option within the question",
                        verbose_name="Order",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="Question this answer option belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_options",
                        to="catalog.question",
                        verbose_name="Question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Answer Option",
                "verbose_name_plural": "Answer Options",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="testbank",
            index=models.Index(
                fields=["category", "is_active"], name="catalog_tes_categor_afe01c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testbank",
            index=models.Index(fields=["slug"], name="catalog_tes_slug_c72319_idx"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["test_bank", "is_active"], name="catalog_que_test_ba_99836c_idx"
            ),
        ),
    ]
