# Generated by Django 4.2.26 on 2025-11-15 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the certification or exam",
                        max_length=200,
                        verbose_name="Certification Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of the name",
                        max_length=200,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the certification",
                        verbose_name="Description",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order of this certification within the subcategory",
                        verbose_name="Order",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Certification",
                "verbose_name_plural": "Certifications",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the subcategory",
                        max_length=200,
                        verbose_name="SubCategory Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of the name",
                        max_length=200,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the subcategory",
                        verbose_name="Description",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order of this subcategory within the category",
                        verbose_name="Order",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "SubCategory",
                "verbose_name_plural": "SubCategories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                help_text="Category this subcategory belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="catalog.category",
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="certification",
            name="subcategory",
            field=models.ForeignKey(
                help_text="SubCategory this certification belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certifications",
                to="catalog.subcategory",
                verbose_name="SubCategory",
            ),
        ),
        migrations.AlterField(
            model_name="testbank",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Category this test bank belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_banks",
                to="catalog.category",
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="testbank",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                help_text="SubCategory this test bank belongs to (optional)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_banks",
                to="catalog.subcategory",
                verbose_name="SubCategory",
            ),
        ),
        migrations.AddField(
            model_name="testbank",
            name="certification",
            field=models.ForeignKey(
                blank=True,
                help_text="Certification this test bank belongs to (optional)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_banks",
                to="catalog.certification",
                verbose_name="Certification",
            ),
        ),
        migrations.AddIndex(
            model_name="testbank",
            index=models.Index(
                fields=["subcategory", "is_active"],
                name="catalog_tes_subcate_8f7ae7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="testbank",
            index=models.Index(
                fields=["certification", "is_active"],
                name="catalog_tes_certifi_9a7f44_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subcategory",
            index=models.Index(
                fields=["category", "order"], name="catalog_sub_categor_484063_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subcategory",
            unique_together={("category", "slug")},
        ),
        migrations.AddIndex(
            model_name="certification",
            index=models.Index(
                fields=["subcategory", "order"], name="catalog_cer_subcate_181b05_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="certification",
            unique_together={("subcategory", "slug")},
        ),
    ]
