# Generated by Django 4.2.26 on 2025-11-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_certification_subcategory_alter_testbank_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Image/icon for the category card",
                null=True,
                upload_to="categories/",
                verbose_name="Category Image",
            ),
        ),
    ]
