# Generated by Django 4.2.26 on 2025-11-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="testbank",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Image/thumbnail for the test bank card",
                null=True,
                upload_to="testbanks/",
                verbose_name="Test Bank Image",
            ),
        ),
    ]
