# Generated by Django 4.2.26 on 2025-11-16 21:49

from django.db import migrations, models


def migrate_difficulty_levels(apps, schema_editor):
    """Migrate existing difficulty levels from old to new values."""
    TestBank = apps.get_model('catalog', 'TestBank')
    
    # Map old values to new values
    difficulty_mapping = {
        'beginner': 'easy',
        'intermediate': 'medium',
        'advanced': 'advanced',  # stays the same
    }
    
    # Update all test banks
    for test_bank in TestBank.objects.all():
        old_level = test_bank.difficulty_level
        if old_level in difficulty_mapping:
            test_bank.difficulty_level = difficulty_mapping[old_level]
            test_bank.save(update_fields=['difficulty_level'])


def reverse_migrate_difficulty_levels(apps, schema_editor):
    """Reverse migration: map new values back to old values."""
    TestBank = apps.get_model('catalog', 'TestBank')
    
    # Reverse mapping
    reverse_mapping = {
        'easy': 'beginner',
        'medium': 'intermediate',
        'advanced': 'advanced',  # stays the same
    }
    
    # Update all test banks
    for test_bank in TestBank.objects.all():
        new_level = test_bank.difficulty_level
        if new_level in reverse_mapping:
            test_bank.difficulty_level = reverse_mapping[new_level]
            test_bank.save(update_fields=['difficulty_level'])


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_testbank_image"),
    ]

    operations = [
        # First, migrate the data
        migrations.RunPython(migrate_difficulty_levels, reverse_migrate_difficulty_levels),
        # Then, alter the field
        migrations.AlterField(
            model_name="testbank",
            name="difficulty_level",
            field=models.CharField(
                choices=[
                    ("easy", "Easy"),
                    ("medium", "Medium"),
                    ("advanced", "Advanced"),
                ],
                default="easy",
                help_text="Difficulty level of the test bank",
                max_length=20,
                verbose_name="Difficulty Level",
            ),
        ),
    ]
