# Generated by Django 4.2.26 on 2025-11-30 17:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0005_update_difficulty_levels"),
    ]

    operations = [
        migrations.AddField(
            model_name="testbank",
            name="average_rating",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Average rating (0.00 to 5.00)",
                max_digits=3,
                verbose_name="Average Rating",
            ),
        ),
        migrations.AddField(
            model_name="testbank",
            name="total_ratings",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Total number of ratings received",
                verbose_name="Total Ratings",
            ),
        ),
        migrations.CreateModel(
            name="TestBankRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        help_text="Rating from 1 to 5 stars",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                (
                    "review",
                    models.TextField(
                        blank=True,
                        help_text="Optional review text",
                        verbose_name="Review",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "test_bank",
                    models.ForeignKey(
                        help_text="Test bank being rated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="catalog.testbank",
                        verbose_name="Test Bank",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who gave the rating",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_bank_ratings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Bank Rating",
                "verbose_name_plural": "Test Bank Ratings",
                "ordering": ["-created_at"],
                "unique_together": {("user", "test_bank")},
            },
        ),
    ]
