# Generated by Django 4.2.26 on 2025-12-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_add_ratings_and_user_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="testbankrating",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Optional title for the review",
                max_length=200,
                verbose_name="Review Title",
            ),
        ),
    ]
