# Generated by Django 4.2.26 on 2025-12-07 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0007_testbankrating_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Reply content",
                        max_length=1000,
                        verbose_name="Content",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "review",
                    models.ForeignKey(
                        help_text="Review being replied to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="catalog.testbankrating",
                        verbose_name="Review",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who wrote the reply",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_replies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Reply",
                "verbose_name_plural": "Review Replies",
                "ordering": ["created_at"],
            },
        ),
    ]
