# Generated by Django 4.2.26 on 2025-12-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_reviewreply"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the person sending the message",
                        max_length=200,
                        verbose_name="Name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address for response",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Subject of the message",
                        max_length=200,
                        verbose_name="Subject",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="The message content", verbose_name="Message"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the message has been read by an admin",
                        verbose_name="Is Read",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "ordering": ["-created_at"],
            },
        ),
    ]
