# Generated by Django 4.2.26 on 2026-02-21 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0012_remove_subcategory_domain_models"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="certification",
            name="catalog_cer_subcate_181b05_idx",
        ),
        migrations.RemoveIndex(
            model_name="testbank",
            name="catalog_tes_subcate_8f7ae7_idx",
        ),
        migrations.AlterField(
            model_name="certification",
            name="category",
            field=models.ForeignKey(
                help_text="Category this certification belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certifications",
                to="catalog.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="certification",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Order of this certification within the category",
                verbose_name="Order",
            ),
        ),
        migrations.AddField(
            model_name="certification",
            name="difficulty_level",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("advanced", "Advanced")],
                default="easy",
                help_text="Difficulty level of the certification",
                max_length=20,
                verbose_name="Difficulty Level",
            ),
        ),
        migrations.AlterField(
            model_name="testbank",
            name="certification_domain",
            field=models.CharField(
                blank=True,
                help_text="Subject area or domain of the certification (e.g., Information Technology, Healthcare) - metadata field",
                max_length=200,
                null=True,
                verbose_name="Certification Domain",
            ),
        ),
        migrations.AddIndex(
            model_name="certification",
            index=models.Index(
                fields=["category", "order"], name="catalog_cer_categor_163e9f_idx"
            ),
        ),
    ]
