# Generated by Django 4.2.26 on 2026-02-23 20:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0014_update_certification_unique_constraint"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="certification",
            new_name="catalog_cer_categor_e86e81_idx",
            old_name="catalog_cer_categor_diffic_idx",
        ),
    ]
