# Generated by Django 4.2.26 on 2026-02-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "catalog",
            "0015_rename_catalog_cer_categor_diffic_idx_catalog_cer_categor_e86e81_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="testbank",
            name="time_limit_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Time limit for practice sessions in minutes (null for no time limit)",
                null=True,
                verbose_name="Time Limit (minutes)",
            ),
        ),
    ]
