# Generated by Django 6.0.2 on 2026-02-25 01:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_rename_catalog_cer_categor_diffic_idx_catalog_cer_categor_e86e81_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certification',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='testbankrating',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='certification',
            constraint=models.UniqueConstraint(fields=('category', 'slug', 'difficulty_level'), name='unique_certification_per_category_difficulty'),
        ),
        migrations.AddConstraint(
            model_name='testbankrating',
            constraint=models.UniqueConstraint(fields=('user', 'test_bank'), name='unique_rating_per_user_testbank'),
        ),
    ]
