# Generated by Django 4.2.26 on 2026-02-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0016_testbank_time_limit_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="official_url",
            field=models.URLField(
                blank=True,
                help_text="Official website URL for the certification or organization",
                max_length=500,
                null=True,
                verbose_name="Official URL",
            ),
        ),
    ]
