# Generated by Django 6.0.2 on 2026-02-25 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_certification_unique_together_and_more'),
        ('catalog', '0017_certification_official_url'),
    ]

    operations = [
    ]
