# Generated by Django 4.2.26 on 2026-03-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0018_merge_20260225_2113"),
    ]

    operations = [
        migrations.AddField(
            model_name="testbank",
            name="attempts_per_purchase",
            field=models.PositiveIntegerField(
                default=3,
                help_text="Number of exam attempts granted per purchase (e.g., 1, 3, or 999 for unlimited)",
                verbose_name="Attempts Per Purchase",
            ),
        ),
    ]
