# Generated by Django 4.2.26 on 2026-03-19 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0019_add_attempts_per_purchase"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Package name (e.g., CompTIA Starter Pack)",
                        max_length=200,
                        verbose_name="Title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of the title",
                        max_length=200,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the package contents",
                        verbose_name="Description",
                    ),
                ),
                (
                    "package_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Discounted price for the bundle",
                        max_digits=10,
                        verbose_name="Package Price",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this package is visible and purchasable",
                        verbose_name="Is Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Exam Package",
                "verbose_name_plural": "Exam Packages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamPackageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "exam_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="catalog.exampackage",
                    ),
                ),
                (
                    "test_bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_items",
                        to="catalog.testbank",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("exam_package", "test_bank")},
            },
        ),
        migrations.AddField(
            model_name="exampackage",
            name="test_banks",
            field=models.ManyToManyField(
                blank=True,
                help_text="Test banks included in this package",
                related_name="exam_packages",
                through="catalog.ExamPackageItem",
                to="catalog.testbank",
                verbose_name="Test Banks",
            ),
        ),
        migrations.AddIndex(
            model_name="exampackage",
            index=models.Index(fields=["slug"], name="catalog_exa_slug_1b637a_idx"),
        ),
        migrations.AddIndex(
            model_name="exampackage",
            index=models.Index(
                fields=["is_active"], name="catalog_exa_is_acti_2efdcc_idx"
            ),
        ),
    ]
