# Generated by Django 4.2.26 on 2026-04-17 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0020_add_exam_package"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Domain/topic name (e.g. "Networking Fundamentals")',
                        max_length=150,
                        verbose_name="Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier (unique per test bank)",
                        max_length=150,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description shown in analytics",
                        verbose_name="Description",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order in analytics breakdowns",
                        verbose_name="Order",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "test_bank",
                    models.ForeignKey(
                        help_text="Test bank this domain belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="catalog.testbank",
                        verbose_name="Test Bank",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Domain",
                "verbose_name_plural": "Question Domains",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                help_text="Topic/domain for analytics grouping (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="catalog.questiondomain",
                verbose_name="Domain",
            ),
        ),
        migrations.AddIndex(
            model_name="questiondomain",
            index=models.Index(
                fields=["test_bank", "order"], name="catalog_que_test_ba_4116cb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="questiondomain",
            constraint=models.UniqueConstraint(
                fields=("test_bank", "slug"), name="unique_domain_slug_per_testbank"
            ),
        ),
    ]
