# Generated by Django 4.2.26 on 2026-04-17 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0021_questiondomain_question_domain_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            (
                                "brain_dump",
                                "Appears to be from a real exam (NDA/copyright concern)",
                            ),
                            ("factual_error", "Factually wrong"),
                            ("wrong_answer", "Wrong answer marked as correct"),
                            ("typo", "Typo or formatting issue"),
                            ("outdated", "Outdated / no longer relevant"),
                            ("other", "Other"),
                        ],
                        default="factual_error",
                        max_length=32,
                        verbose_name="Reason",
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="Optional extra context from the reporter",
                        max_length=2000,
                        verbose_name="Details",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("under_review", "Under review"),
                            ("resolved", "Resolved — fixed"),
                            ("dismissed", "Dismissed — no action"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "resolution_note",
                    models.TextField(
                        blank=True,
                        help_text="Admin note describing what was done",
                        max_length=2000,
                        verbose_name="Resolution note",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        help_text="The question being reported",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="catalog.question",
                        verbose_name="Question",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who reported (null if user later deleted)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="question_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reporter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Report",
                "verbose_name_plural": "Question Reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="catalog_que_status_c8fbfd_idx",
                    ),
                    models.Index(
                        fields=["question", "status"],
                        name="catalog_que_questio_7f0eff_idx",
                    ),
                    models.Index(
                        fields=["reason", "status"],
                        name="catalog_que_reason_974e61_idx",
                    ),
                ],
            },
        ),
    ]
